version: '3.9'

services:
  rabbitmq1:
    image: rabbitmq:3.8-management
    ports:
      - 15673:15672
      - 5673:5672
    hostname: rabbitmq1
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
  rabbitmq2:
    image: rabbitmq:3.8-management
    ports:
      - 15674:15672
      - 5674:5672
    hostname: rabbitmq2
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
  rabbitmq3:
    image: rabbitmq:3.8-management
    ports:
      - 15675:15672
      - 5675:5672
    hostname: rabbitmq3
    restart: always
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
  haproxy1:
    image: haproxy:2.5.7
    ports:
      - 8001:8001
      - 8002:8002
      - 15676:15672
    hostname: haproxy1
    restart: always
    volumes:
      - ./haproxy-etc:/usr/local/etc/haproxy:ro
  haproxy2:
    image: haproxy:2.5.7
    ports:
      - 8011:8001
      - 8012:8002
      - 15677:15672
    hostname: haproxy2
    restart: always
    volumes:
      - ./haproxy-etc:/usr/local/etc/haproxy:ro
