version: '3.9'

services:
  rabbitmq1:
    image: rabbitmq:3.8-management
    container_name: rabbitmq1
    ports:
      - 15673:15672
      - 5673:5672
    hostname: rabbitmq1
    restart: always
    volumes:
      - rabbitmq-data-1:/var/lib/rabbitmq
      - rabbitmq-logs-1:/var/log/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
  rabbitmq2:
    image: rabbitmq:3.8-management
    container_name: rabbitmq2
    ports:
      - 15674:15672
      - 5674:5672
    hostname: rabbitmq2
    restart: always
    volumes:
      - rabbitmq-data-2:/var/lib/rabbitmq
      - rabbitmq-logs-2:/var/log/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
  rabbitmq3:
    image: rabbitmq:3.8-management
    container_name: rabbitmq3
    ports:
      - 15675:15672
      - 5675:5672
    hostname: rabbitmq3
    restart: always
    volumes:
      - rabbitmq-data-3:/var/lib/rabbitmq
      - rabbitmq-logs-3:/var/log/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=rabbitcookie
  haproxy1:
    image: haproxy:2.5.7
    container_name: rabbitmq-haproxy1
    ports:
      - 8000:8000
      - 5672:5672
      - 15672:15672
    hostname: haproxy1
    restart: always
    volumes:
      - ./haproxy-etc:/usr/local/etc/haproxy:ro
  haproxy2:
    image: haproxy:2.5.7
    container_name: rabbitmq-haproxy2
    ports:
      - 8001:8000
      - 5676:5672
      - 15676:15672
    hostname: haproxy2
    restart: always
    volumes:
      - ./haproxy-etc:/usr/local/etc/haproxy:ro

volumes:
  rabbitmq-data-1: {}
  rabbitmq-logs-1: {}
  rabbitmq-data-2: {}
  rabbitmq-logs-2: {}
  rabbitmq-data-3: {}
  rabbitmq-logs-3: {}
