version: '3.9'

services:
  redis-main:
    image: redis:6.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-main.conf:/usr/local/etc/redis/redis.conf
      - volume-redis-main:/data
  redis-replica:
    image: redis:6.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis-replica.conf:/usr/local/etc/redis/redis.conf
      - volume-redis-replica:/data
  mongo:
    image: mongo:4.4.5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - volume-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - 3306:3306
    volumes:
      - volume-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sandbox
  rebbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - volume-rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

volumes:
  volume-redis-main: {}
  volume-redis-replica: {}
  volume-mongo: {}
  volume-mysql: {}
  volume-rabbitmq: {}