version: '3.9'

services:
  redis-main:
    image: redis:6.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    hostname: redis-main
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis-main.conf:/usr/local/etc/redis/redis.conf
      - volume-redis-main:/data
  redis-replica:
    image: redis:6.2.3
    command: redis-server /usr/local/etc/redis/redis.conf
    hostname: redis-replica
    restart: always
    ports:
      - 6380:6379
    volumes:
      - ./redis-replica.conf:/usr/local/etc/redis/redis.conf
      - volume-redis-replica:/data
  mongo:
    image: mongo:4.4.5
    hostname: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - volume-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  mysql:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    hostname: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - volume-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: sandbox
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - volume-rabbitmq:/var/lib/rabbitmq
      - volume-rabbitmq-log:/var/log/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
  postgresql:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    volumes:
      - volume-postgresql:/var/lib/postgresql


volumes:
  volume-redis-main: {}
  volume-redis-replica: {}
  volume-mongo: {}
  volume-mysql: {}
  volume-rabbitmq: {}
  volume-rabbitmq-log: {}
  volume-postgresql: {}

